### ISSUE TITLE
Increase number of successfully parsed projects available in the platform

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/jenkins-ingest#54]
The goal of this issue is to increase the number of successfully parsed projects available in the platform, such that users of public.moderne.io can run recipes against a large collection of Open Source projects, and the ingestion process can handle a large variety of project configurations.

```
39092 projects in repos.csv
 5242 of which are currently skipped, and will likely remain so
29587 are available in https://public.moderne.io, some of which only with a failed output log
 4263 projects must then fail to ingest in any form to the platform (failed output log or parsed LST)
```

There's a number of different ways we can analyze current failures, depending on their failure mode, and try to fix these.

```[tasklist]
### Tasks
- [ ] [Run through the parser flow](https://github.com/moderneinc/jenkins-ingest/blob/main/parser/README.md) to skip outdated wrappers and update Java versions periodically.
- [ ] Cluster the errors found in the failed output logs through the [FindBuildToolFailures data tables](https://public.moderne.io/recipes/org.openrewrite.FindBuildToolFailures).
- [ ] Inspect failures in Jenkins that have not produced failure output logs to the platform.
- [ ] https://github.com/moderneinc/infra/issues/433
```

**Comment by kmccarp** [comment]
@timtebeek Is there any plan to continue work on this? If not can we close it out?

**Comment by timtebeek** [comment]
We do still want to improve the number of parsed projects, as we've seen in the past that some of the issues we identified here before occur at customers as well; I've removed the item from the Moderne Engineering board, such it's now only on the DevEx team board, hope that helps.

**Comment by timtebeek** [comment]
We're now only incidentally fixing ingestion issues, and tracking improvements on a Grafana dashboard. Ok to close this issue as it's not actively picked up by itself.
